name: Main
on:
  push:

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npm run build

  publish:
    name: Publish
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npm run build
        working-directory: ./packages/react

      #   # To the public NPM Registry
      #   - uses: actions/setup-node@v3
      #     with:
      #       node-version: "18.x"
      #       registry-url: "https://registry.npmjs.com"
      #   - run: npm config list
      #   - run: npm publish
      #     env:
      #       NODE_AUTH_TOKEN: ${{ secrets.PUBLIC_NPM_REGISTRY_TOKEN }}

      # To the Github Package Registry
      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          registry-url: "https://npm.pkg.github.com"
      - run: npm config list

      - run: npm publish
        working-directory: ./packages/react
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
