name: Release
on:
  push:
    tags:
      - "*"

jobs:
  create-github-release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')

    permissions:
      contents: "write"

    steps:
      - uses: actions/checkout@v3
      - uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  publish-package-to-registries:
    runs-on: ubuntu-latest
    needs: [create-github-release]
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npm run build

      #   # To the public NPM Registry
      #   - uses: actions/setup-node@v3
      #     with:
      #       node-version: "18.x"
      #       registry-url: "https://registry.npmjs.com"
      #   - run: npm config list
      #   - run: npm publish
      #     env:
      #       NODE_AUTH_TOKEN: ${{ secrets.PUBLIC_NPM_REGISTRY_TOKEN }}

      # To the Github Package Registry
      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          registry-url: "https://npm.pkg.github.com"
      - run: npm config list
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
